# Generated by Django 2.2 on 2019-04-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('COP_CompanyID', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('COP_CompanyName', models.CharField(max_length=255)),
                ('COP_CompanyAddress', models.CharField(max_length=255)),
                ('COP_CompanyOwner', models.CharField(max_length=255)),
                ('COP_DateOfFormation', models.DateField(max_length=8)),
                ('COP_TimeStamp', models.DateField(auto_now=True)),
            ],
        ),
    ]
